
version: '3.8'

services:
  nginx-gateway:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
